
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author msi
 */
public class VisuJoueursDlg extends javax.swing.JDialog {
    private LesJoueurs lj;
    /**
     * Creates new form VisuJoueursDlg
     */
    public VisuJoueursDlg(java.awt.Frame parent, boolean modal, LesJoueurs lesj) {
        super(parent, modal);//appel du constructeur de la classe ancetre 
        initComponents();//cr&ation de l'interface par l'EDI
        this.lj = lesj;//affecte le tableau de joueur passé en parametre a l'attribut lj
        initTrombi();//methode pour afficher des boutons vides dans le JPanel
    }

   private void initTrombi()
    { int nb = this.lj.getNbJoueurs();//recupere la taille du tableau
       PPhoto.setLayout(new GridLayout(1, nb));
        for (int i=0; i< nb; i++){
            JButton jb= new JButton();//crée un bouton
            Joueur j= lj.getJoueur(i);
            jb.setName(""+i);
            jb.addActionListener(new java.awt.event.ActionListener() { //on abonne le bouton a un ecouteur d'evenement
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            AfficheInfosJoueur(evt);//methode pour afficher les informations du joueur sur on a cliqué sur le JPanel
 }
 }); 
            PPhoto.add(jb);//ajoute le bouton au JPanel
 }
 this.pack();
         }
  
   private void AfficheInfosJoueur(java.awt.event.ActionEvent evt) {
       JButton jb = (JButton) evt.getSource();//recupere le bouton qui a ete cliqué
       String n = jb.getName();//recupere son name
       int num = Integer.parseInt(n);//convertit en int
       if(num>=0 && num<this.lj.getNbJoueurs()){
           Joueur j = this.lj.getJoueur(num);//recupere le joueur correspondant a l'indice
           Edition.setText(j.toString());//affiche ses informations dans la zone d'edition
   }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PPhoto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BAfficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre.setText("Choisissez un joueur pour voir ses caractéristiques");
        getContentPane().add(Titre, java.awt.BorderLayout.PAGE_START);

        PCentre.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout PPhotoLayout = new javax.swing.GroupLayout(PPhoto);
        PPhoto.setLayout(PPhotoLayout);
        PPhotoLayout.setHorizontalGroup(
            PPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        PPhotoLayout.setVerticalGroup(
            PPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        PCentre.add(PPhoto);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        PCentre.add(jScrollPane1);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        BAfficher.setText("Afficher");
        BAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAfficherActionPerformed(evt);
            }
        });
        getContentPane().add(BAfficher, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAfficherActionPerformed
    for (int i=0; i< this.lj.getNbJoueurs(); i++){
           JButton jb = (JButton) PPhoto.getComponent(i);
           Joueur j = this.lj.getJoueur(i);
           Image img = j.getPhoto().getImage().getScaledInstance(jb.getWidth(),jb.getHeight(),Image.SCALE_DEFAULT);
           jb.setIcon(new ImageIcon(img));
       }
    }//GEN-LAST:event_BAfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAfficher;
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PPhoto;
    private javax.swing.JLabel Titre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
