
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class VisuPersonnageDlg extends javax.swing.JDialog {
    private Joueur j;//attribut de type Joueur

    /**
     * Creates new form VisuPersonnageDlg
     */
    public VisuPersonnageDlg(java.awt.Frame parent, boolean modal, Joueur j) {
        super(parent, modal);//appel du constructeur ancetre 
        initComponents();// création de l'interface par l'EDI
        this.j = j;//affecte le joueur passé en parametre a l'attribut j
        jPseudo.setText("Cartes du joueur : "+this.j.getPseudo()); //affiche le pseudo dans la JLabel
        jScore.setText("Score : "+j.getScore());//affiche  le score du joueur dans la JLabel
        initPanneau();// méthode pour afficher les boutons dans le JPanel
        
    }
    
 
    
    private void initPanneau() { 
        LesPersonnages lp = j.getPaquet(); // recupere le paquet du joueur 
        int n = lp.getTaille(); // recupere la taille du paquet 
        int nc = (int)(Math.sqrt(n*2)); // intialisation du nombre de colonnes calculé
        int nl = (int)((n*2/nc)-1); // intialisation du nombre de lignes calculé
        Panneau.setLayout(new GridLayout(nl,nc)); // donner au Panneau un GridLayout de nl Lignes et nc Colonnes
        for(int i=0;i<n;i++){
            JButton bt = new JButton(); //Création d'un nouveau bouton
            Panneau.add(bt); // ajouter au Panneau le bouton crée 
            
            this.pack(); 
        }
         }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau = new javax.swing.JPanel();
        jPseudo = new javax.swing.JLabel();
        PBas = new javax.swing.JPanel();
        jScore = new javax.swing.JLabel();
        BAfficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPseudo, java.awt.BorderLayout.NORTH);

        PBas.setLayout(new java.awt.GridLayout(2, 1));
        PBas.add(jScore);

        BAfficher.setText("Afficher");
        BAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAfficherActionPerformed(evt);
            }
        });
        PBas.add(BAfficher);

        getContentPane().add(PBas, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAfficherActionPerformed
          LesPersonnages lp = j.getPaquet();  // recupere le paquet du joueur 
        for(int i=0;i<lp.getTaille();i++){  
            JButton bt = (JButton) Panneau.getComponent(i);       // recupere le bouton d'indice i dans le JPanel
            Image img = lp.getPerso(i).getPhoto().getScaledInstance(bt.getWidth(),bt.getHeight(),Image.SCALE_DEFAULT);//redimenssionne l'image
            ImageIcon photo = new ImageIcon(img);//convertir l'image en ImageIcon et l'affecte a la variable photo
            bt.setIcon(photo);//affiche l'image dans le bouton
        } 
    }//GEN-LAST:event_BAfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnageDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnageDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnageDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuPersonnageDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAfficher;
    private javax.swing.JPanel PBas;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jPseudo;
    private javax.swing.JLabel jScore;
    // End of variables declaration//GEN-END:variables
}
